---
# handlers file for icinga2-ansible-add-hosts

- name: restart icinga2
  service: name=icinga2
           state=restarted
           enabled=yes
  become: true         

- name: reload icinga2
  service: name=icinga2
           state=reloaded
           enabled=yes
  become: true
