---
- name: Install Nrpe
  yum: name=nrpe state=latest
  become: true
  
- name: Disable SELinux
  selinux: state=disabled
  become: true
  
- name: Install Nagios plugins
  yum: name=nagios-plugins-all  state=latest
  become: true
  
- name: Install Nrpe Plugin
  yum: name=nagios-plugins-nrpe state=latest
  become: true
  
- name: Install Check_Mem_Ng
  get_url: url=https://raw.githubusercontent.com/zwindler/check_mem_ng/master/check_mem_ng.sh
           dest=/usr/lib64/nagios/plugins/check_mem_ng
           mode=0755
  become: true
           
- name: Copy Nrpe Configuration
  template: src=nrpe.cfg.j2
            dest=/etc/nagios/nrpe.cfg
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - restart nrpe
  become: true

- name: Start nrpe
  service: name=nrpe state=started enabled=yes
  become: true