---
- name: Install httpd web server.
  yum: name=httpd state=installed
  become: true
  when: ansible_os_family == 'RedHat'
      
- name: Ensure httpd is started and enabled on boot.
  service: name=httpd state=started enabled=yes
  become: true
      
- name: Copy httpd virtual hosts file in place.
  copy: src='../files/vhosts.conf' dest='/etc/httpd/conf.d/site.conf' mode=0644
  notify: restart httpd
  become: true
      
- name: Creating dir for new site
  file: path='/usr/share/httpd/site' state='directory' mode=0755
  become: true
   
- name: Index page for new site
  template: src='../templates/index.html.j2' dest='/usr/share/httpd/site/index.html' mode=0644 owner='root'
  become: true
  notify: restart httpd