---
- hosts: all
  gather_facts: True
  
- hosts: web
  roles:
      - epel-repo
      - nrpe
      - web
 
- hosts: haproxy
  roles:
      - epel-repo
      - nrpe
      - ha

- hosts: ecinga
  roles:
      - epel-repo
      - icinga2
      - icinga2-ui
      - nrpe
      - icinga2-new-host